### PR TITLE
Deprecate rule EC4 for Java because not applicable

### LINKED ISSUE #233: [EC4][Java] Rule is not applicable to Java
**Describe the bug**
The rule "avoid global variables" is not applicable to Java.

The history: the first rules were inspired by web best practices, and transposed to other languages without analysis due to lack of time. This shows in the description of this rule, which shows JS.

Scope is not an issue in Java, and constants are a best practice for readability and memory optimization. EC4 _is not_ applicable to Java and should be removed.

### PR DESCRIPTION
**Pull request by utarwyn**
After discussion in #233, we confirmed that the rule "Use global variables" was not applicable to the Java language.
This PR therefore removes it completely from the Java plugin and rules specifications.

~~I've decided to remove it rather than deprecate it, as it proposes incorrect information that I don't think should be left in the plugin. This way, they should no longer appear in SonarQube analyses, as soon as an instance has been updated.~~

Thanks for the discussion and feedback on this rule. It's how we manage to fine-tune the plugin and come up with the most relevant rules possible.

Resolves #233

### CODE REVIEW

**Review by dedece35 — CHANGES_REQUESTED** [review]
I don't understand why delete it instead of make it deprecated .
For me  deprecation is also to remember that EC4 was an old rule id and not to use this rule id in future rule.
For me it's not clear when do we deprecate or delete one rule.
@glalloue, @jhertout, @utarwyn, @olegoaer ?

**Comment by jhertout** [comment]
Hello,

I agree with @dedece35, I think we must depreciate the rule in a first time if we want to be rigorous. Since our plugin is public I think it is important for us to try to follow this process even if I understand that it can be frustrating.

**Comment by utarwyn** [comment]
I will deprecate it first, you are right. Let me change this. But I will need #242 in order to do it properly. We can discuss the process around rule deprecation/deletion during the next meeting if you want.

**Comment by utarwyn** [comment]
In order to have a smoother transition before the rule deletion, I have deprecated it. You can see the result in the SonarQube UI below. It will now be necessary to define how long it remains deprecated, but this will be discussed at the next meeting. I kept the unit test and implementation, to keep it working before everyone turned it off in quality profiles.

image

**Comment by dedece35** [comment]
to discuss in core-team : deprecation if this rule

**Review by dedece35 — APPROVED** [review]

**Pull request merged**
