### PR TITLE
Adapt Grsp0008 php

### PR DESCRIPTION
**Pull request by oussamaLaribi**
- Adapt description.
- Fix deprecated code.
- Merge from main.

### CODE REVIEW

**Comment by dedece35** [comment]
hi @oussamaLaribi 
why do you close this PR ?

**Comment by oussamaLaribi** [comment]
> hi @oussamaLaribi why do you close this PR ?

Hi @dedece35, I haven't finished yet this PR, once I've finished, I'll open it again.

**Comment by oussamaLaribi** [comment]
> > hi @oussamaLaribi why do you close this PR ?
> 
> Hi @dedece35, I haven't finished yet this PR, once I've finished, I'll reopen it.

**Comment by dedece35** [comment]
Hi @oussamaLaribi ,

you can modify state of your PR to "draft". then, your PR cannot be merged will you didn't finish your work.

**Comment by oussamaLaribi** [comment]
> Hi @oussamaLaribi ,
> 
> you can modify state of your PR to "draft". then, your PR cannot be merged will you didn't finish your work.
> 
> another thing, sorry for my previous comment because I didn't see that your PR will merge your private branch to another branch, and not to main branch. That-s why, it's ok for me.

Hi @dedece35, Okay Thanks.

**Review by dedece35 — APPROVED** [review]
Hi @oussamaLaribi ,

I approved this MR to your branch and I modify the PR https://github.com/green-code-initiative/ecoCode/pull/6 to draft.
Please, merge these 2 PRs when you are ready.

**Comment by oussamaLaribi** [comment]
> Hi @oussamaLaribi ,
> 
> I approved this MR to your branch and I modify the PR #6 to draft. Please, merge these 2 PRs when you are ready.

Hi @dedece35, Okay it's ready to be merged with PR #6.Thanks

**Pull request merged**
