### PR TITLE
[EC34][Java][5R] - Rules "try..catch.."

### PR DESCRIPTION
**Pull request by Silicoman**
Issue #101 

Pour partage avec autre équipe

### CODE REVIEW

**Comment by wokier** [comment]
This rule will create too many warning
other way using existing rule: https://github.com/green-code-initiative/ecoCode-common/pull/15

**Comment by Silicoman** [comment]
@Ella-dee , be inform about your work. :)  As we discuss on team meeting, it's difficult without details rules. It will generate too many warnings false-positive without more restricted implementation.

**Comment by utarwyn** [comment]
Based on previous comments and recent work made on custom tags, is this PR still relevant?

I am also afraid of the number of warnings that this rule will cause: we are clearly on a language-based rule and not a platform one. And I am not sure that the impact is that significant compared to the constraints it will bring. What do you think of this?

**Comment by dedece35** [comment]
waiting ofr discussion inside core-team with issue #173

**Comment by dedece35** [comment]
TODOs for me : 

- [ ] replace rule with specific example with FileNotFoundException
   - ecocode-rules-specifications implementation
   - Java implementation
   - PHP implementation
   - RULES.md doc
- [ ] check other issues / PR on the same subject
   - PHP : #173 and https://github.com/green-code-initiative/ecoCode-php/issues/8
   - #115

**Comment by dedece35** [comment]
After all discussions on this EC34 rule for Java , python and PHP, here are conclusions :
- Python : like described above, EC34 was deprecated and transformed to EC35 with more specific checks
- PHP : same as Python, check above
- Java : neither EC34 rule isn't applicable nor EC35. For this one, file open process must be try-catch even if an exist control of file is done before try

thus, sorry @Silicoman, but I have to refused this PR for Java and close the referenced issue.

**Pull request closed without merging**
