### PR TITLE
Add java rule EC24: Optimize Database SQL Queries (Clause LIMIT)

### PR DESCRIPTION
**Pull request by dedece35**
update rule-specifications for issue https://github.com/green-code-initiative/ecoCode/issues/239

### CODE REVIEW

**Review by utarwyn — COMMENTED** [review]
Would it make more sense to implement the [EC24](https://github.com/green-code-initiative/ecoCode/blob/main/ecocode-rules-specifications/src/main/rules/EC24/javascript/EC24.asciidoc) rule for java rather than create a new one? This rule is not in the ecoCode `RULES.md` file, only the one in the JavaScript repository, which isn't very clear, I admit...

**Review by utarwyn — APPROVED** [review]

**Comment by Djoums** [comment]
The rule makes sense but I don't see how it's going to be implemented. There are many ways to write SQL queries, and that's not even considering ORMs.

**Comment by dedece35** [comment]
Hi @Djoums,
I agree with you that there are a lot of ways to write one SQL query, and this is very difficult sometimes to check how these queries are built and what is the final SQL query really executed.
But, for me, we can implement the easiest way, firstly : if we detect a SQL query built inside a string, thus we can check if "limit" keyword is used or not. I'm ok with you, this use case is the easiest and I don't know if it's often used or not, but, these use cases will be detected.
what do you think about it ?

**Comment by Djoums** [comment]
Actually I don't think you can do it, even for the most basic cases. What if the dev writes this : _string test = "select * from table"_. Are you going to raise a warning ? You don't know if that query will be executed or not, and you don't know if it will be limited or not (maybe there's _test += " limit 25"_ somewhere later). You're going to raise a lot of false positives.

The way I see it, a code analyzer cannot enforce this rule. This would be a job for the query engine in the DBMS, because it's the only component that knows exactly what's going to be executed and how.

**Pull request merged**
