### PR TITLE
[ISSUE 64] python plugin : refactoring and corrections

### PR DESCRIPTION
**Pull request by dedece35**
As mentionned on ISSUE 64, python rules system was not OK since our upgrade of lib versions and for SonarQube 9.9.
Done on python plugin :
- clean maven config
- complete existing rules and change tag `eco-conception` to `eco-design` (as recommended in an other issue)
- refactor central classes of plugin

### CODE REVIEW

**Comment by jhertout** [comment]
Just by curiosity, why do you remove all the Json for all the rules? I think it was clearer with them than having all the rules properties in the source code. It is just my advice though.

**Comment by dedece35** [comment]
@jhertout 
I removed JSON files because with the refactoring of main plugin classes, these files were not used to initialize rules.
maybe this refactoring was not the best way, but I spent a lot of time to analyse the problem and no precise help found on Web.
once python and php plugins UP ... I will spend time to put the same system as Java and mobiles plugins (maybe a particular extension to add : maybe a registrat extension).
now we have a python test project to check that plugin works.
I am going to create PHP test project for the same pb on PHP plugin

**Comment by jhertout** [comment]
OK, thanks. It was to know what is the good way to proceed for our rules. We will do without the json.

**Comment by dedece35** [comment]
@jhertout,
I think that plugins currently working with JSON files must be kept like that.
I did it for python plugin because I looked for a simple and quick solution for python plugin problem.
I think I will dod the same for PHP plugin (that has the same problem).
But after hackathon, I think, I come back to these solutions to check why the previous method didn't work.
These problems (Python and PHP) was the good thing to introduce test projects.

**Comment by jhertout** [comment]
Yes, we will do without the json only for the Python rules. We will keep the json for the other plugins. I think it is a better way to do when we can. Since we need our Python rule before the hackaton, I can't wait a potential refactor. We will create the json later during the python project refactor if necessary.

**Pull request merged**
