### PR TITLE
Prefer collections with pagination (team 106 critères)

### PR DESCRIPTION
**Pull request by Pima-Dev**
Add prefer-collections-with-pagination rule documentation
The rule content can be found at https://github.com/green-code-initiative/ecoCode-linter/pull/6

### CODE REVIEW

**Comment by dedece35** [comment]
Hi @utarwyn, could please make the review in order to close quickly this PR to migrate this code to js repository please ?

**Comment by utarwyn** [comment]
Hello, I'm waiting for the PR https://github.com/green-code-initiative/ecoCode-linter/pull/10 to be integrated before this one, as this breaks a common file which will be in conflict otherwise. I will read this one right after the merge.

**Comment by utarwyn** [comment]
Done in [29e40a7](https://github.com/green-code-initiative/ecoCode/commit/29e40a7f55ebebfc96065bb547b6f36075e29297)

**Comment by dedece35** [comment]
@utarwyn have you thought about upgrading CHANGELOG.md ? :p

**Pull request closed without merging**
