### PR TITLE
[Ec7][java][python][5R] update rules not to do and exemple for py

### PR DESCRIPTION
**Pull request by Silicoman**
-> EC7[JAVA] : Getter/Setter custom à ne pas implementer
Non implementable. Il y a forcement des getters/setters pour accéder aux attributs d’une classe. L’utilization d’une lib Lombok pour l’auto-generation n’a pas d’avantage green  (Exemple: Ajout d’une dependance à un projet)
- update rules.md

-> EC7[Python] : Getter/Setter custom à ne pas implementer
- Correction d’incohérence dans l’exemple qui implemente un getter.
Suppression du tag « bug » qui n’en est pas un

### CODE REVIEW

**Comment by Silicoman** [comment]
Issue #123

**Review by dedece35 — CHANGES_REQUESTED** [review]
Hi @Silicoman,

could please make the correction of conflicts, please ?

**Comment by dedece35** [comment]
Hi @Silicoman 
please resolve conflict and then check DoD list here https://github.com/green-code-initiative/ecoCode-common/blob/main/doc/starter-pack.md#definition-of-done-of-a-pr

**Comment by dedece35** [comment]
check retour sur PHP dans l'issue

**Comment by dedece35** [comment]
Task done : 
- https://github.com/green-code-initiative/ecoCode/pull/262 : update resources 
- PRs on Python repositories
   - https://github.com/green-code-initiative/ecoCode-python/pull/11
   - https://github.com/green-code-initiative/ecoCode-python-test-project/pull/8
- PRs on java repositories
   - TODO
- PRs on PHP repositories
   - TODO

**Comment by dedece35** [comment]
PR closed because modifications done on differents repositories (now, we have one repository by language for ecocode).
all is ok.
thank you a lot @Silicoman

**Pull request closed without merging**
