### PR TITLE
Adapt Grsp0007 php 

### PR DESCRIPTION
**Pull request by oussamaLaribi**
-Merge from the main
-Remove rule GRSP0008 from the PR
-Adapt description.

### CODE REVIEW

**Comment by dedece35** [comment]
HI @oussamaLaribi, why this big PR have so commits ?
Maybe start from old PR of cnumr organization to see what code changed and then report here ?

**Comment by dedece35** [comment]
Hi @oussamaLaribi ,

as I said in other PR,

Hi @oussamaLaribi ,

you can modify state of your PR to "draft". then, your PR cannot be merged will you didn't finish your work.

another thing, sorry for my previous comment because I didn't see that your PR will merge your private branch to another branch, and not to main branch. That-s why, it's ok for me.

**Comment by oussamaLaribi** [comment]
> Hi @oussamaLaribi ,
> 
> as I said in other PR,
> 
> Hi @oussamaLaribi ,
> 
> you can modify state of your PR to "draft". then, your PR cannot be merged will you didn't finish your work.
> 
> another thing, sorry for my previous comment because I didn't see that your PR will merge your private branch to another branch, and not to main branch. That-s why, it's ok for me.

Hi @dedece35, okay thanks.

**Review by dedece35 — APPROVED** [review]

**Comment by dedece35** [comment]
Hi @oussamaLaribi ,

I approved this MR to your branch and I modify the PR #5 to draft.
Please, merge these 2 PRs when you are ready.

**Comment by oussamaLaribi** [comment]
> Hi @oussamaLaribi ,
> 
> I approved this MR to your branch and I modify the PR #5 to draft. Please, merge these 2 PRs when you are ready.

Hi @dedece35, Okay it's ready to be merged with PR #5.Thanks

**Pull request merged**
