### PR TITLE
Resolve issue CRJVM204 [Team 1.5]

### PR DESCRIPTION
**Pull request by nouk-pl**
Resolved issue [CRJVM204](https://github.com/orgs/green-code-initiative/projects/1?pane=issue&itemId=16188668.)

### Summary
Because SVGs are generally smaller than other image format, they’re less taxing on your server despite needing to render on load. So we recommended, when it is possible, to use svg format image over other image format.

SVG are vector image, they can be compress without any loss, witch means that they're compressible to smaller file sizes at no cost to their definition, detail, or quality. PNGs also benefit from lossless compression of 5-20%, which can help make up for their large file size. However, they're still likely to be larger than an SVG.

SVGs are also scalable and will render pixel-perfect at any resolution whereas JPEGs, PNGs and GIFs will not.

### How it work ?
To check if a not recommended image format are used in Java code, we check string literal to verify if a not recommended extension is used. If so, an issue is raised.

### On SonarQube

The render of an issue explanation :

image

### CODE REVIEW

**Comment by MP-Aubay** [comment]
Issue #105

**Comment by dedece35** [comment]
hi @nouk-pl,
please resolve conflicts and check DoD list here : https://github.com/green-code-initiative/ecoCode-common/blob/main/doc/starter-pack.md#definition-of-done-of-a-pr

**Comment by dedece35** [comment]
HI @utarwyn, @jhertout, @glalloue,

what do you think about this PR ?
I have a doubt about implementation that constraints strongly the use of all image formats.

**Comment by dedece35** [comment]
core-team decision : not applicable as described
argumentation to do by @jycr, please.

**Comment by jycr** [comment]
Sorry, I'm coming late to the discussion of this proposed rule.

Imposing SVG as the only valid format is not relevant.

Indeed, SVG can only be used for specific kind of images (those presenting drawings or solid colors: e.g. icons, logos).

A photographic illustration will be of much better quality for a lower size by remaining in a “bitmap” format (eg: JPG, WebP).
Vectorizing a bitmap image will degrade the quality and increase its weight.

Here is an example with the image used on the home page of https://www.greenpeace.fr/ :

Original Bitmap image in JPG (75 ko -> 73 ko through HTTP GZIP) :

Cheetah-Nathan-Moine-2-1600x900

Vectorized Image in SVG (2,3 Mo -> 1,9 Mo through HTTP GZIP) :

Cheetah-Nathan-Moine-2-1600x900



The context and applicability of this rule need to be much better clarified.
Based on the applicability criteria, we need to see if it is possible to automatically determine whether this rule can apply.
In any case, we should not apply this rule systematically

**Comment by dedece35** [comment]
PR closed, for now, because not applicable like that : see explanation above.
Feel free to reopen linked issue and this PR once work (measures, clarification) done

**Pull request closed without merging**
