### PR TITLE
create new rust plugin (manual from @dedece35) 

### PR DESCRIPTION
**Pull request by dedece35**
initial PR (before migration): https://github.com/cnumr/ecoCode/pull/134
(plop @Azel-ytof )

### CODE REVIEW

**Comment by dedece35** [comment]
Hi @Azel-ytof,
can you please correct conflicts, please ?
then I will review it.
thank you.

**Comment by glalloue** [comment]
Hi @Azel-ytof or @dedece35 : do you think we can unlock this PR before ecoCode challenge ? 
it could be great to have it ready for the event if someone wanted to add some new rules based on rust

**Comment by Azel-ytof** [comment]
Hi @glalloue 
It all depends if there are still things to do
What are your needs ?

**Comment by dedece35** [comment]
Hi @Azel-ytof,
for me, the first need is the correction of conflicts, please :p

**Comment by Azel-ytof** [comment]
Hey,
I have just check this, and I think we could drop this PR.
It is complex to merge it, it may be easier to do this from scratch.

**Comment by dedece35** [comment]
Hi @Azel-ytof ,
ok. I close this PR.
Feel free to open a new one with your rust contribution :p 

thank you

**Pull request closed without merging**
