### PR TITLE
Add CONTRIBUTING.MD and CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by dedece35**

### CODE REVIEW

**Comment by dedece35** [comment]
First submition of CONTRIBUTING.md and CODE_OF_CONDUCT.md
nexts step : get starter_pack info and some of my best practices (unit tests, check stringly the code)

**Comment by jhertout** [comment]
Good start for me. It makes the project more "official".

For the section "Some rules from experience", I imagine you have not finished but for the rule you added "Protections against ClassCast exceptions" why did you not add it directly in Programming Practices"? I am not sure it is a good idea to have an other section that talks about "Programming Practices" after the "Tests" section. I find this confusing and it is like these last rules are less important than the others before while there are not.

**Comment by dedece35** [comment]
Hi @jhertout,
I've just finished my modifications with my last commit. Please check it.
I keep "Some rules from experience" as last section because, there are all experience tips like "ClassCast exception" or "unit tests".

**Comment by jhertout** [comment]
Hello @dedece35,

I persist to think that the rules "Protections against ClassCast exceptions" should be in the section  "Programming Practices" and "Unit tests" in tests. There are "from experiences" but when I see them here at the end of the document in this section, I feel like there are less important than the others just because there are **our** rules. But well, it just my opinion and it can stay like this if we want.

An other point: you put a table of contents in the Contributing.md file. I think it is a good idea and maybe we should have one, at least in the CODE_STYLE.md, to quickly remind the rules without having to go through the document.

I quickly go through the English of the files and cannot see mistakes but I am not a specialist.

Except these points, the documents are very clear and give a good entry point for new users (and old users too :)).

**Comment by dedece35** [comment]
Hi @jhertout,

modifications wanted done.
thank you for review.

**Pull request merged**
