### PR TITLE
CRJVM208 - Avoid spring repository calls in loops with Stream

### PR DESCRIPTION
**Pull request by ibhmefteh**

### CODE REVIEW

**Comment by MP-Aubay** [comment]
Duplicate https://github.com/green-code-initiative/ecoCode/pull/151

**Comment by dedece35** [comment]
Issue #112

**Comment by dedece35** [comment]
Hi @kerimboukadida and @ibhmefteh,
please correct the problem with checks ("checks" tab)  : error on building

**Comment by dedece35** [comment]
Hi @ibhmefteh,
I've just upgraded your PR with last modifications but crash on build (with compiler errors). 
please make corrections.

**Comment by dedece35** [comment]
I close this PR because of stale status.
I decided to create a new PR #238 to merge code of this PR (#157 ) and #151  one with also some improvements : check content of #238

**Pull request closed without merging**
