### PR TITLE
[S90-JAVA] Avoid use of static in interface

### PR DESCRIPTION
**Pull request by dedece35**
initial PR (before migration): https://github.com/cnumr/ecoCode/pull/183
(plop @ggeoffroy68 )

### CODE REVIEW

**Comment by dedece35** [comment]
Hi @ggeoffroy68,
I checked SonarQube native rules. I found rule with id `java:S1214`wich deal with the same subject.

Does a documention or tests exist to prove the rightness of your rule ?

**Comment by dedece35** [comment]
to discuss in core-team : 
- no scientific paper to prove this rule
- no argument to prove it's a "green" rule
- there is aleady a native Sonarqube rule to deal with this rule approximatively ("java:S1214")

for me, rule not acceptable like that.
do we refuse this rule ?

**Comment by jhertout** [comment]
Hello,

difficult for me to validate a rule like this without a minimum of justification. This requires at least some benchmark. May be we should keep it in mind for the future hackathon since I think it is quite easy to perform measures on a rule like this if we have the tools.

**Comment by dedece35** [comment]
Hi @ggeoffroy68,

sorry but with implementation is that situation, we can't accept this implementation because : 
- no scientific paper to prove this rule
- no measures to prove it's a "green" rule
- there is already a native Sonarqube rule to deal with this rule approximatively ("java:S1214")

We keep this proposition to measure it when we will have a tool to measure it.
(check [RULES.md](https://github.com/green-code-initiative/ecoCode/blob/main/RULES.md#rules-to-be-reworked--measured--clarified) )

**Pull request closed without merging**
