### PR TITLE
Add rule "Prefer lighter formats for image files"

### PR DESCRIPTION
**Pull request by utarwyn**
Hello,
I want to propose a new rule in the ecoCode repository. You can find its declaration below.
What do you think of it?

## Platform

JavaScript (React / JSX) and HTML in the future

## Main caracteristics

| ID | Title | Category |
|----------|----------------------|-------------|
| EC31 | Prefer lighter formats for image files | Network, Power consumption |

## Severity / Remediation Cost

I propose a remediation cost of 5min per image, in order to convert it to another format, based on needs.

| Severity | Remediation Cost |
|------------|---------------------|
| Minor | 5min |

## Rule complete description

Check asciidoc in the PR content.

## Implementation principle

- Check for file extensions used in `` elements
- Also check for imported files in the JavaScript/TypeScript code
- Do not check for `` elements inside `<picture>` elements, because its used to support multiple formats (to support older browsers for example)

### CODE REVIEW

**Comment by dedece35** [comment]
Hi @utarwyn,
I think it's a good idea but do you check if there isn't this kind of rule in Sonarqube or in other existing rules ?
@olegoaer, a point of view ?

**Comment by utarwyn** [comment]
@dedece35 
I've checked: this rule does not appear in the list of rules proposed by SonarQube. However, this rule limits the image formats that can be used to reduce the carbon footprint of a website, so it's probably too "restrictive" for them and not about clean code.

**Comment by olegoaer** [comment]
Indeed. `.webp` and `.avif` are best formats on website ([see this study](https://greenspector.com/en/which-image-format-to-choose-to-reduce-its-energy-consumption-and-its-environmental-impact/))

This rule is clearly about green code, not clean code :)

**Comment by utarwyn** [comment]
Thank you for the feedback! I will add this reference into rule documentation.

**Review by dedece35 — APPROVED** [review]

**Pull request merged**
