### PR TITLE
Correct the display

### PR DESCRIPTION
**Pull request by tecbiio**
The code was written in a language similar to php for the java plugin, there was also an inconsistent display

### CODE REVIEW

**Comment by dedece35** [comment]
Hi @tecbiio ,
thank you for your contribution.
But please respect the template of issue creation (when we create an issue, we must choose a template : bug or feature template). If you can give us some snapshot (like mentionned in template), it would be great.
Please, upgrade your branch too.

**Comment by tecbiio** [comment]
Hi @dedece35,
Where can i find the templates ?

**Comment by dedece35** [comment]
Hi @tecbiio ,

the template is automatic when you create a new issue ... you must choose between "bug report", "feature request" or "Report a security vulnerability".

**Review by dedece35 — CHANGES_REQUESTED** [review]
please add some explanations to issue.

**Pull request closed without merging**
