### PR TITLE
Add images to the description files.

### PR DESCRIPTION
**Pull request by oussamaLaribi**
Add an image to the description of rule s72 [PHP].

### CODE REVIEW

**Review by dedece35 — COMMENTED** [review]
Hi @oussamaLaribi
I don't understand why you want to add an JPG image to docker instances

What is the purpose ?

**Comment by oussamaLaribi** [comment]
> Hi @oussamaLaribi I don't understand why you want to add an JPG image to docker instances
> 
> What is the purpose ?

Hi @dedece35, I tried with just the image source, but it is not loaded into the Sonor Qube description rule when I start docker instances. So I decided to add it to the instance and it worked.

**Comment by dedece35** [comment]
Hi @oussamaLaribi,
I've juste tested locally your PR but it is'nt ok for me, sorry. Several problems : 
- tool build docker image and start it, I must 
    - modify docker-compose.yml to change 0.1.0-SNAPHOT versions to 0.1.1-SNAPSHOT version
    - next, change `source: common` to `source: ./common`
- after SonarQube started, the image is broken (check joined capture) where image URL is `http://localhost:9000/opt/sonarqube/common/images/php/s72_percent_comparison.jpg` : for me it can't work because this url path is not exposed on SonarQube
    - i found some other images on SonarQube server where images are stored on directory `/opt/sonarqube/images`

please check again

**Comment by oussamaLaribi** [comment]
> Hi @oussamaLaribi, I've juste tested locally your PR but it is'nt ok for me, sorry. Several problems :
> 
> * tool build docker image and start it, I must
>   
>   * modify docker-compose.yml to change 0.1.0-SNAPHOT versions to 0.1.1-SNAPSHOT version
>   * next, change `source: common` to `source: ./common`
> * after SonarQube started, the image is broken (check joined capture) where image URL is `http://localhost:9000/opt/sonarqube/common/images/php/s72_percent_comparison.jpg` : for me it can't work because this url path is not exposed on SonarQube
>   
>   * i found some other images on SonarQube server where images are stored on directory `/opt/sonarqube/images`
> 
> for now, I d'ont have a solution, sorry, but please make checks again
> 
> Capture d’écran 2022-12-22 à 21 58 37

Hi @dedece35, Okay I'll check it. Thanks.

**Comment by oussamaLaribi** [comment]
Hi, @dedece35. I used a different option. I used Flickr for storing pictures it's free. "Flickr is a media platform used for uploading, organizing, and sharing digital media such as photos and videos."

**Review by dedece35 — CHANGES_REQUESTED** [review]
please add a comment in changelog file, in "unreleased" part

**Comment by oussamaLaribi** [comment]
> please add a comment in changelog file, in "unreleased" part

Hi @dedece35, Okay I'll do it. Thanks.

**Review by dedece35 — APPROVED** [review]

**Pull request merged**
