### PR TITLE
Adding SonarQube-ecoCode container image (manual from @dedece35)

### PR DESCRIPTION
**Pull request by dedece35**
initial PR (before migration): https://github.com/cnumr/ecoCode/pull/137
(plop @obeone )

### CODE REVIEW

**Comment by dedece35** [comment]
Hi @obeone,
Did you have time to resolve conflicts of this PR to progress our ideas ?

**Comment by glalloue** [comment]
Hi @obeone , i relaunch you concerning this PR.
This branch has some conflicts, is it possible for you to fix it ?

**Comment by obeone** [comment]
Ohh I’m deeply sorry !
I do my best to work on it this week !

**Comment by obeone** [comment]
Working on it ! I’ll probably create a new PR, to many changes since this one, I think it will be easier to start again on a clean branch

**Comment by dedece35** [comment]
Hi @obeone,
ok thank you.
I am ok to review if needed.

**Comment by dedece35** [comment]
PR canceled because of #72

**Pull request closed without merging**
